default_stages: [ commit, push ]
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [
          --line-length=100,
          --target-version=py311
        ]
        exclude: ^(venv/|docs/)
        types: [ 'python' ]
